---
title: "Reticulate 101"
subtitle: "Introdução ao uso de reticulate para facilitar a integração entre códigos R e Python"
author: "<br>Luis Henrique Zanandréa Paese<br>"
date: "<br>Janeiro 2021"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["style/shinobi.css", "ninjutsu", "style/ninpo.css"]
    self_contained: false
    nature: 
      ratio: "16:9"
      highlightStyle: monokai-sublime
      highlightLines: true
      countIncrementalSlides: false
      seal: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(echo = FALSE, eval = T, warning = F, message = F, dev = 'svg')
```

class: middle bg-main1 hide-slide-number

.outline[
## Outline

* Introdução
* Configuração do Reticulate
* Importando/instalando pacotes
  * Importação de Pacotes
  * Importação de funções
  * Python console
* R Environment/Py Environment
* Live Coding
]

---
```{r Intro, child='sections/01_introduction.Rmd'}
```

```{r Why_Use, child='sections/02_reticulate_config.Rmd'}
```

```{r How_To, child='sections/03_importando_pacotes.Rmd'}
```

```{r Examples, child='sections/04_r_py_env.Rmd'}
```

```{r Conclusions, child='sections/05_conclusion.Rmd'}
```

```{r Live_Demo, child='sections/06_livedemo.Rmd'}
```